name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Unit tests for core domain
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Run unit tests
        run: dotnet test src/WorkshopManagement.UnitTests --no-build --verbosity normal

  # UI tests with Selenium
  ui-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      # Install Chrome browser
      - name: Install Chrome
        run: sudo apt-get install -y google-chrome-stable

      # Match ChromeDriver version with Chrome version
      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v1
        with:
          chrome-version: 'latest' # Match installed Chrome version

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the solution
      - name: Build
        run: dotnet build --no-restore

      # Run UI tests
      - name: Run UI tests
        run: dotnet test src/UITest --no-build --verbosity normal
